# Generated by Django 4.2.1 on 2023-06-05 15:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stores", "0005_alter_variation_product"),
        ("carts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cartitem",
            name="variations",
            field=models.ManyToManyField(blank=True, to="stores.variation"),
        ),
    ]
